---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Webserver down
      condition: event.payload.event == "apache service down"
  ## Define the action we should take should the condition be met
      action:
        #pretty: true
        run_workflow_template:
          name: "SH - WORKFLOW - WEB"

