---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Webserver down
      condition: event.payload.event == "ola"
      action:
        debug:
          msg: Simple debug message
